version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 5001:5001
    environment:
      - DATABASE_URL=postgresql+asyncpg://todo_app:1234@db:5432/todo_app_dev
    volumes:
      - ./services/backend:/app
    command: uvicorn src.api:app --reload --host 0.0.0.0 --port 5001
    depends_on:
      - db

  frontend:
    build: ./services/todo-app
    volumes:
      - './services/todo-app:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
      
  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=todo_app
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=todo_app_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: